import os
import re
import pandas as pd
from glob import glob
from datetime import datetime

configfile: os.path.join('config', 'config.yaml')

### Setting variables ###

outdir = config['outdir']
info_df = pd.read_csv(config['metadata'], sep = '\t').set_index('sample', drop=False)
bt2_index_dir = os.path.join(config['references'], 'bowtie2_index')


## source helper functions + fixed variables
include: os.path.join("rules", "common.smk")

## define targets
#@ conditionally getting symlinks if data generated at Seqcore
solexa = []

if config['data_source'] == 'Solexa':
    solexa.append('%s/_fastq/get_solexa_links.log' %outdir)
    
rule all:
    input: 
        get_targets,
        solexa


rule link_solexa:
    input: config['metadata']
    #@ use log as output here to avoid splitting due to different output defined by wcs
    output: os.path.join(outdir, '_fastq/get_solexa_links.log')
    params: 
        outpath = os.path.join(outdir, '_fastq')
    message: "Getting fastq files from Solexa"
    shell:
        """
        scripts/get_solexa_symlinks {input} {params.outpath} 2> {output}
        """


include: os.path.join("rules", "pre-processing.smk")
include: os.path.join("rules", "processing.smk")
include: os.path.join("rules", "QC.smk")
