import os
import re
import pandas as pd
from glob import glob
from datetime import datetime

configfile: os.path.join('config', 'config.yaml')

#outdir = datetime.now().strftime('%Y%m%d')
# if not os.path.exists(outdir):
#     os.makedirs(outdir)

outdir = config['outdir']
    
info_df = pd.read_csv(config['metadata'], sep = '\t').set_index('sample', drop=False)

include: os.path.join("rules", "common.smk")

rule all:
    input: 
        os.path.join(outdir, 'get_symlinks.log'),
        get_targets


## use log as output here to avoid splitting based on different output defined w wcs
rule link_fastq:
    input: config['metadata']
    output: os.path.join(outdir, 'get_symlinks.log')
    params: 
        outpath = os.path.join(outdir, '_fastq')
    shell:
        """
        scripts/get_solexa_symlinks {input} {params.outpath} 2> {output}
        """


include: os.path.join("rules", "pre-processing.smk")
include: os.path.join("rules", "processing.smk")
include: os.path.join("rules", "QC.smk")
