### GENERAL ###
metadata: /project/ibr_procs/dev/pipe_dev/ChIP-ATAC_processing/sample_info_test.tsv
outdir: /project/ibr_procs/dev/pipe_dev/ChIP-ATAC_processing/test/20240531


### REFERENCES ###
ref_dir: /project/MDL_Ibrahim/MP_all/references
